### ISSUE TITLE
At what point does simp_le renew certs?

### ISSUE THREAD

**Issue by marcaddeo** [kuba/simp_le#77] opened 2016-02-25 14:55 UTC
How many days left on a cert does simp_le wait until it automatically renews the cert? I just got an alert from lets encrypt saying our certs have 15 days left so just wanna check.

**Comment by kuba** [comment] 2016-02-27 22:04
It should renew if you run it within one month before expiry.

Closing, as otherwise this would be a duplicate of #74.

**Closed as completed by kuba** 2016-02-27 22:04 UTC
