### ISSUE TITLE
AttributeError: 'X509' object has no attribute '_req'

### ISSUE THREAD

**Issue by pawal** [kuba/simp_le#73] opened 2016-02-11 15:01 UTC
After running bootstrap and venv.sh:

```
blog$~/cert/simp_le>./simp_le.py --email x@x.x -f key.pem -f cert.pem -f chain.pem -f account_key.json -d x.x --default_root /usr/share/wordpress
Traceback (most recent call last):
  File "./simp_le.py", line 1390, in main
    return main_with_exceptions(cli_args)
  File "./simp_le.py", line 1370, in main_with_exceptions
    if valid_existing_cert(existing_data.cert, args.vhosts, args.valid_min):
  File "./simp_le.py", line 1193, in valid_existing_cert
    existing_sans = pyopenssl_cert_or_req_san(cert)
  File "./simp_le.py", line 1161, in pyopenssl_cert_or_req_san
    return crypto_util._pyopenssl_cert_or_req_san(cert)
  File "/usr/lib/python2.7/dist-packages/acme/crypto_util.py", line 178, in _pyopenssl_cert_or_req_san
    text = func(OpenSSL.crypto.FILETYPE_TEXT, cert_or_req).decode("utf-8")
  File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 2346, in dump_certificate_request
    result_code = _lib.X509_REQ_print_ex(bio, req._req, 0, 0)
  File "/usr/lib/python2.7/dist-packages/acme/jose/util.py", line 42, in __getattr__
    return getattr(self.wrapped, name)
AttributeError: 'X509' object has no attribute '_req'

Unhandled error has happened, traceback is above
```

These are the package versions reported of I run bootstrap again:

ca-certificates is already the newest version (20160104).
gcc is already the newest version (4:5.3.1-1).
libffi-dev is already the newest version (3.2.1-4).
libssl-dev is already the newest version (1.0.2f-2).
python is already the newest version (2.7.11-1).
python-dev is already the newest version (2.7.11-1).
virtualenv is already the newest version (1.11.6+ds-1).

**Comment by FrancisRussell** [comment] 2016-02-22 19:26
I'm getting this under a Debian testing installation. I reverted simp_le back to master at the time it last successfully retrieved my certs (around December) and that broke too suggesting an external library has changed its interface.

**Comment by FrancisRussell** [comment] 2016-02-22 19:57
OK, I've debugged this a bit further. 

In the function _pyopenssl_cert_or_req_san() in ACME, there's an isinstance check on the variable cert_or_req to see if it's a cert or a request. This value's been wrapped in a ComparableX509 meaning that the isinstance check gets the wrong result and everything breaks after this. ComparableX509 a wrapper defined by ACME so it looks like this is where the bug is. I've opened an issue [here](https://github.com/letsencrypt/letsencrypt/issues/2526).

**Comment by bmw** [comment] 2016-02-22 22:59
dupe of #70

**Comment by FrancisRussell** [comment] 2016-02-22 23:05
No, it's not and it looks like the complete opposite. The bug you referenced was due to simp_le not passing a wrapped object to acme. In this case, simp_le is doing the right thing, but acme is failing to handle the wrapped object correctly.

**Comment by bmw** [comment] 2016-02-22 23:13
Ah. You're correct the error is different, but I suspect the cause is the same. Based on the traceback, I can see that you're not using version 0.1.0 of the `acme` library which is required by `simp_le`.

**Comment by FrancisRussell** [comment] 2016-02-22 23:17
That is true and therefore an unsupported configuration for simp_le. However, the bug still appears to be with acme. If I understand things correctly, acme defines a number of wrappers which clients are supposed to use, but acme breaks because it can't handle the wrapper when a wrapped object is passed back in.

**Comment by FrancisRussell** [comment] 2016-02-22 23:20
OK, I just read your response to the bug report against letsencrypt which suggests things should be fixed in simp_le.

**Comment by kuba** [comment] 2016-02-27 22:09
`/usr/lib/python2.7/dist-packages/acme/jose/util.py` -> you are mixing PyPI and OS packages - that's not supported mode of operation, please use virtualenv.

**Closed as completed by kuba** 2016-02-27 22:09 UTC
